export enum Event {
  Connect = "connection",
  Disconnect = "disconnect",
  GetUser = "user/get-one",
  GetUsers = "user/get-all",
  GetUserStatus = "user/get-status",
  SetUserStatus = "user/set-status",
  ActiveUser = "user/active",
  UpdateUser = "user/update",
  DelGroup = "group/del",
  Message = "chat/message",
  Register = "register",
  Login = "login",
  AddFriend = "firend/add",
  DelFriend = "firend/del",
  GetFriends = "friend/get",
  JoinRoom = "room/join",
  CreateGroup = "group/create",
  GetGroups = "group/get-all",
  JoinGroup = "group/join",
}
