export const USER_LOGIN_REQUIES = 'USER_LOGIN_REQUIES';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_REGISTER_REQUIES = 'USER_REGISTER_REQUIES';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const ADD_FRIEND_REQUIES = 'ADD_FRIEND_REQUIES';
export const ADD_FRINED_SUCCESS = 'ADD_FRINED_SUCCESS';
export const ADD_FRINED_FAIL = 'ADD_FRINED_FAIL';

export const GET_FRIEND_REQUIES = 'GET_FRIEND_REQUIES';
export const GET_FRINED_SUCCESS = 'GET_FRINED_SUCCESS';
export const GET_FRINED_FAIL = 'GET_FRINED_FAIL';

export const SET_ACTIVE_USER = 'SET_ACTIVE_USER';

export const SHOW_CHAT_SMALL_SCREEN = 'SHOW_CHAT_SMALL_SCREEN';
export const HIDE_CHAT_SMALL_SCREEN = 'HIDE_CHAT_SMALL_SCREEN';

export const GET_GROUPS_REQUIES = 'GET_GROUPS_REQUIES';
export const GET_GROUPS_SUCCESS = 'GET_GROUPS_SUCCESS';
export const GET_GROUPS_FAIL = 'GET_GROUPS_FAIL';

export const SET_ACTIVE_GROUP = 'SET_ACTIVE_GROUP';
export const UPDATA_PROFILE_PHOTO = 'UPDATA_PROFILE_PHOTO';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

export const REMOVE_FRIEND_REQUEST = 'REMOVE_FRIEND_REQUEST';
export const REMOVE_FRIEND_SUCCESS = 'REMOVE_FRIEND_SUCCESS';
export const REMOVE_FRIEND_FAIL = 'REMOVE_FRIEND_FAIL';
export const SEARCH_FRIENDS = 'SEARCH_FRIENDS';
export const SEARCH_GROUPS = 'SEARCH_GROUPS';
